// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJmtncAyeRvqYKZP0CpfWMfScFwiA1QZQ',
    appId: '1:330997345510:web:1cc7d973ef2e2389059f27',
    messagingSenderId: '330997345510',
    projectId: 'mwis-inventory',
    authDomain: 'mwis-inventory.firebaseapp.com',
    storageBucket: 'mwis-inventory.firebasestorage.app',
    measurementId: 'G-3KSDMTDQ8V',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXaJnTv8CDOO556ZobOxqwS3hIbKzWMFQ',
    appId: '1:330997345510:ios:1fe37ed3ffefc2c8059f27',
    messagingSenderId: '330997345510',
    projectId: 'mwis-inventory',
    storageBucket: 'mwis-inventory.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXaJnTv8CDOO556ZobOxqwS3hIbKzWMFQ',
    appId: '1:330997345510:ios:1fe37ed3ffefc2c8059f27',
    messagingSenderId: '330997345510',
    projectId: 'mwis-inventory',
    storageBucket: 'mwis-inventory.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLTiketKq_in7Efyf7yp_F-Gbwdhdl1RY',
    appId: '1:330997345510:android:a09f881ebbff680c059f27',
    messagingSenderId: '330997345510',
    projectId: 'mwis-inventory',
    storageBucket: 'mwis-inventory.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJmtncAyeRvqYKZP0CpfWMfScFwiA1QZQ',
    appId: '1:330997345510:web:3aced7240ed60069059f27',
    messagingSenderId: '330997345510',
    projectId: 'mwis-inventory',
    authDomain: 'mwis-inventory.firebaseapp.com',
    storageBucket: 'mwis-inventory.firebasestorage.app',
    measurementId: 'G-916SRYRFV8',
  );
}
